language: php

php:
    - 5.6
    - hhvm

env:
    - PHP_BIN=php

matrix:
    allow_failures:
        - php: hhvm
  
script:
    - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source

deploy:
    provider: opsworks
    access-key-id: AKIAJHNPJYOBRJCG2EQA
    secret-access-key:
        secure: IPNAly0uLi2jYaqnRU1l5HL0bREfDj7qrZoVtmcIXjNViVurYCGUa5oFIRYYnpFyyjQ1s5WdcGxjzxwhxue+4gbiDVfkantitwIMpP1fr5kLpRvXGZRvZMMi1rH7GxxwYUgeeijv9HnwyfTfAO0GvxPlqUIoNoIoc8769QpRyiE=
    app-id: 5796c69d-7dec-4614-bd6e-c030d536b6d8
