language: php
php:
    - 5.3.3
    - 5.6
    - hhvm

env:
    - PHP_BIN=php

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source